/*
 * FILE: ch_i.c
 *
 * DESCRIPTION: From 'N' points, search for those that enclose the rest of them, genetaring a polygon.
 *
 * AUTHOR: Alonso Maripi Vallejos & Silvana Cerda Aravena
 *
 * LAST REVISED: Santiago de Chile, 04/11/2016
 *
 */

 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
 #include <time.h>
 #include <math.h>
 #define MAX 110L

 struct point// Basic estructure of a point in the X-Y axis
 {
    double x;
    double y;
  };

struct point S[MAX];
int cont = 0;

int exist(struct point j){//Function that determinate if a point already exist in the list that determinate the polygon.
    int i;
    for(i = 0;i < cont;i++){
        if(S[i].x == j.x && S[i].y == j.y)
          return 1;

    }
    return 0;
}

double evaluate(struct point i,struct point j,struct point m){ //Function that get the value of the point evaluated in the line generated by other two points.
    return ((m.x - i.x)/(j.x - i.x)) - ((m.y - i.y)/(j.y - i.y));
}

void work (struct point i,struct point j,struct point M[MAX],int n){ //Function that set if a point is part of the polygon that enclose the rest of them.
    int m,flag = 0;
    double A;

    for(m = 0;m < n; m++){

        if (M[m].x != j.x && M[m].y != j.y && M[m].x != i.x && M[m].y != i.y){

            if(j.x - i.x != 0 && j.y - i.y != 0){ //When both points that are evaluating the rest of them have diferent values on the X and Y axis.

                A = evaluate(i,j,M[m]);
                if(A > 0){
                    if(flag == 0 || flag == 1)
                        flag = 1;
                    else
                        flag = -1;
                }
                else{
                    if(A <= 0){
                        if(flag == 0 || flag == 2)
                            flag = 2;
                        else
                            flag = -1;
                    }
                    else
                        flag = -1;
                }
            }
            else{
                if(j.x - i.x == 0 && j.y - i.y != 0){ // When both point have the same value on the X axis.
                    if(M[m].x > i.x){
                        if(flag == 0 || flag == 1)
                            flag = 1;
                        else
                            flag = -1;
                    }
                    else{
                        if(M[m].x <= i.x){
                          if(flag == 0 || flag == 2)
                              flag = 2;
                          else
                              flag = -1;
                        }
                        else
                            flag = -1;
                    }
                }
                else{
                    if(j.x - i.x != 0 && j.y - i.y == 0){ // When both point have the same value on the Y axis.
                        if(M[m].y > i.y){
                            if(flag == 0 || flag == 1)
                                flag = 1;
                            else
                                flag = -1;
                        }
                        else{
                            if(M[m].y <= i.y){
                              if(flag == 0 || flag == 2)
                                  flag = 2;
                              else
                                  flag = -1;
                            }
                            else
                                flag = -1;
                        }
                    }
                }
            }
        }
    }

    if(flag != -1){
        if(exist(i) == 0){
            S[cont].x = i.x;
            S[cont].y = i.y;
            cont = cont + 1;
        }
        if(exist(j) == 0){
            S[cont].x = j.x;
            S[cont].y = j.y;
            cont = cont + 1;
        }
    }

}

/*
 * Main Function.
 */
int main() {

    int i, j, cont, num;
    double x,y;
    struct point V[MAX];

    float E_cpu;
    clock_t cs, ce;
    long E_wall;
    time_t ts, te;

    for(scanf(" %d",&num),i=0;i<num;i++)
    {
       scanf(" %lf %lf",&x,&y);
       V[i].x=x;
       V[i].y=y;
    }
    ts = time(NULL);
    cs = clock();
    for(i = 0;i < num;i = i + 1){

        for(j = i + 1;j < num;j = j + 1){

            work(V[i],V[j],V,num);

        }
    }
    ce = clock();
    te = time(NULL);

    E_wall = (long) (te - ts);//The diference of time is calculated, to set the time of execution in seconds.
    E_cpu = (float)(ce - cs) / CLOCKS_PER_SEC;//The diference of cpu time is calculated.
    printf("Size Problem: %d Elapsed CPU Time: %f [Secs] Elapsed Wall Time: %ld [Secs]",num,E_cpu,E_wall);
    printf("\n\nVertex of the Polygon :\n");

    for(i = 0;i < cont;i = i + 1)
        printf("(%.2lf,%.2lf) ,",S[i].x,S[i].y  );

    return 0;
}
